ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/dotfiles/custom"
ZSH_THEME="pete"

DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"

setopt auto_cd
setopt auto_pushd
setopt prompt_subst
setopt histignoredups
autoload -Uz compinit && compinit

source $ZSH/oh-my-zsh.sh

# tired of writing this
function include () {
  [[ -f "$1" ]] && . "$1"
}

# load personal settings
include ~/.localrc

# load settings for specific hostnames
include ~/dotfiles/hosts/$(ls ~/dotfiles/hosts | grep $(hostname -s)) 

# load rest of files
for file in ~/dotfiles/bash/*; do
  . "$file"
done

if [[ "$TERM" != "screen" ]] && 
        [[ "$SSH_CONNECTION" == "" ]]; then
    # Attempt to discover a detached session and attach 
    # it, else create a new session

    WHOAMI=$(whoami)
    if tmux has-session -t $WHOAMI 2>/dev/null; then
        tmux -2 attach-session -t $WHOAMI
    else
        tmux -2 new-session -s $WHOAMI
    fi
else
fi
